3.11.5-ol-7-r24 release

diff --git a/bitnami/cassandra/3/ol-7/prebuildfs/usr/local/bin/install_packages b/bitnami/cassandra/3/ol-7/prebuildfs/usr/local/bin/install_packages
--- a/bitnami/cassandra/3/ol-7/prebuildfs/usr/local/bin/install_packages
+++ b/bitnami/cassandra/3/ol-7/prebuildfs/usr/local/bin/install_packages
@@ -1,20 +1,29 @@
 #!/bin/sh
-set -e
-set -u
-n=0
+set -eu
+
+if [[ -n "oracle-epel-release-el7" ]]; then
+    if ! yum list installed oracle-epel-release-el7 >/dev/null 2>&1; then
+        yum -y install oracle-epel-release-el7 >/dev/null 2>&1
+        CODE=$?
+        if (( $CODE != 0 )); then
+          echo "EPEL repository installation failed"
+          exit $CODE
+        fi
+    fi
+fi
+
 max=2
-until [ $n -gt $max ]; do
+for ((n = 1 ; n <= max ; n+=1 )); do
     set +e
     yum --enablerepo base,updates,ol7_developer_EPEL,ol7_optional_latest install -y "$@"
     CODE=$?
     set -e
-    if [ $CODE -eq 0 ]; then
+    if (( $CODE == 0 )); then
         break
     fi
-    if [ $n -eq $max ]; then
+    if (( $n == $max )); then
         exit $CODE
     fi
     echo "yum failed, retrying"
-    n=$(($n + 1))
 done
 rm -r /var/cache/yum
