Detect all commits in a push
Signed-off-by: Fran Mulero <fmulero@vmware.com>

diff --git a/.github/workflows/cd-pipeline.yaml b/.github/workflows/cd-pipeline.yaml
--- a/.github/workflows/cd-pipeline.yaml
+++ b/.github/workflows/cd-pipeline.yaml
@@ -20,26 +20,29 @@ jobs:
       - id: get-container
         name: Get modified containers
         run: |
-          # Using the Github API to detect the files changed as git merge-base stops working when the branch is behind
-          # and jitterbit/get-changed-files does not support pull_request_target
-          URL="https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}"
-          files_changed_data=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X GET -G "$URL")
-          files_changed="$(echo $files_changed_data | jq -r '.files[] | .filename')"
-          # Adding || true to avoid "Process exited with code 1" errors
-          containers_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "containers/[^/]*" | sort | uniq || true)"
-          flavors=($(echo "$files_changed" | xargs dirname | grep -o "containers/[^/]*/[^/]*/[^/]*" | sort | uniq || true))
-          flavors_json=$(printf "%s\n" "${flavors[@]}" | jq -R . | jq -cs .)
-          # Using grep -c as a better alternative to wc -l when dealing with empty strings."
-          num_containers_changed="$(echo "$containers_dirs_changed" | grep -c "containers" || true)"
+          if [[ "${{ github.event.push.forced }}" == "false" ]]; then
+            # Get all commits associated to the push
+            commits=($(echo ${{ github.event.push.commits }} | jq -r '.commits[] | .url'))
+            flavors=()
+            for commit_url in "${commits[@]}"; do
+              # Using the Github API to detect the files changed as git merge-base stops working when the branch is behind
+              files_changed_data=$(curl -s --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X GET -G "$commit_url")
+              files_changed="$(echo $files_changed_data | jq -r '.files[] | .filename')"
+              # Adding || true to avoid "Process exited with code 1" errors
+              flavors+=($(echo "$files_changed" | xargs dirname | grep -o "containers/[^/]*/[^/]*/[^/]*" | sort | uniq || true))
+            done
 
-          if [[ "$num_containers_changed" -le "0" ]]; then
-            # Changes done in the containers/ folder but not inside a container subfolder -> SKIP
-            echo "::set-output name=error::No changes detected in containers. The rest of the tests will be skipped."
-            echo "::set-output name=result::skip"
+            if [[ "${#flavors[@]}" -le "0" ]]; then
+              echo "::set-output name=error::No changes detected in containers. The rest of the tests will be skipped."
+              echo "::set-output name=result::skip"
+            else
+              flavors_json=$(printf "%s\n" "${flavors[@]}" | jq -R . | jq -cs .)
+              echo "::set-output name=result::ok"
+              echo "::set-output name=flavors::${flavors_json}"
+            fi
           else
-            # Changes done in only one container -> OK
-            echo "::set-output name=result::ok"
-            echo "::set-output name=flavors::${flavors_json}"
+            echo "::set-output name=result::skip"
+            echo "::set-output name=error::Forced push detected. CD pipeline will be skipped"
           fi
       # Using actions/github-scripts because using exit 1 in the script above would not provide any output
       # Source: https://github.community/t/no-output-on-process-completed-with-exit-code-1/123821/3
