Remove Automated CI workflow
Signed-off-by: Fran Mulero <fmulero@vmware.com>

diff --git a/.github/workflows/ci-pipeline.yaml b/.github/workflows/ci-pipeline.yaml
--- a/.github/workflows/ci-pipeline.yaml
+++ b/.github/workflows/ci-pipeline.yaml
@@ -8,6 +8,9 @@ on: # rebuild any PRs and main branch changes
     branches:
       - main
       - bitnami:main
+permissions:
+  issues: write
+  pull-requests: write
 env:
   CSP_API_URL: https://console.cloud.vmware.com
   CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
@@ -54,7 +57,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: get-containers
     if: ${{ needs.get-containers.outputs.result == 'ok' && contains(github.event.pull_request.labels.*.name, 'verify') }}
-    name: Verify container
+    name: Verify
     continue-on-error: false
     strategy:
       fail-fast: false
@@ -75,11 +78,21 @@ jobs:
         run: |
           if [[ -d "${{ matrix.container }}" ]]; then
             name="$(echo "${{ matrix.container }}" | awk -F '/' '{print $2}')"
-            # Build a tag based on current SHA
-            tag="$(echo "${{ matrix.container }}" | awk -F '/' -v run_number="${GITHUB_RUN_NUMBER}" '{printf "%s-rc.%s", $3, run_number}')"
-            echo "::set-output name=tag::${tag}"
-            echo "::set-output name=name::${name}"
-            echo "::set-output name=result::ok"
+            tag=""
+            if [[ "${{ github.actor }}" == "bitnami-bot" ]]; then
+              tag="$(grep -oE "org.opencontainers.image.ref.name=\".+\"" ${{ matrix.container }}/Dockerfile | sed -nr "s|org.opencontainers.image.ref.name=\"(.+)\"|\1|p")"
+            else
+              # Build a tag based on current RUN number
+              tag="$(echo "${{ matrix.container }}" | awk -F '/' -v run_number="${GITHUB_RUN_NUMBER}" '{printf "%s-rc.%s", $3, run_number}')"
+            fi
+            if [[ -z "${tag}" ]]; then
+              echo "No tag found for: ${{ matrix.container }}"
+              exit 1
+            else
+              echo "::set-output name=tag::${tag}"
+              echo "::set-output name=name::${name}"
+              echo "::set-output name=result::ok"
+            fi
           else
             # Container folder doesn't exists we are assuming a deprecation
             echo "::set-output name=result::skip"
@@ -95,13 +108,51 @@ jobs:
           # Container name
           VIB_ENV_CONTAINER: ${{ steps.get-container-metadata.outputs.name  }}
           VIB_ENV_TAG: ${{ steps.get-container-metadata.outputs.tag }}
-  verify-all:
+  verification-summary:
     # Ensure all containers passed the verification
     runs-on: ubuntu-latest
-    name: Verify
-    needs: vib-verify
+    name: Verification Summary
+    needs: get-containers, vib-verify
     if: ${{ always() }}
     steps:
-      - name: Verify
-        if: ${{ needs.vib-verify.result != 'success' && needs.vib-verify.result != 'skipped'}}
-        run: exit 1
+      - name: Verification Summary
+        run: |
+          if [[ "${{ needs.get-containers.result }} != "success" ]]; then
+            echo -e "Verification is required."
+            echo " If you've just created this PR, don't worry about this message. Bitnami Team has to review it and make possible the verification."
+            exit 1
+          else
+            if [[ "${{ needs.get-containers.outputs.result }}" == "skip" ]]; then
+              echo "It seems these changes don't involve any container"
+            else
+              if [[ "${{ needs.vib-verify.result }}" != "success" ]]; then
+                echo -e "Verification is required"
+                echo "Please review previous jobs to get more information"
+                exit 1
+              else
+                echo "Well done! Everything looks good. Please wait for the Bitnami Team review."
+              fi
+            fi
+          fi
+      - name: Approval
+        if: ${{ github.actor == 'bitnami-bot' && needs.vib-verify.result == 'success' }}
+        run: |
+          curl --request POST \
+          --url https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews \
+          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
+          --header 'content-type: application/json' \
+          --data '{
+            "event": "APPROVE"
+            }' \
+          --fail
+      - name: Manual review required
+        if: ${{ github.actor == 'bitnami-bot' && needs.vib-verify.result != 'success' }}
+        run: |
+          curl --request POST \
+          --url https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
+          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
+          --header 'content-type: application/json' \
+          --data '{
+            "body": "There has been an error during the automated release process. Manual revision is now required."
+            }' \
+          --fail
